### ISSUE TITLE
VSCode through SSH support

### ISSUE THREAD

**Issue by mchaniotakis** [Octoframes/jupyter_compare_view#39]
It seems that running a remote VSCode session is not displaying the comparison at all (no errors), would this be a VSCode issue instead of a jupyter_compare_view? Is there a way to go around this problem?

Thanks in advance.

**Comment by kolibril13** [comment]
jupyter_compare_view is not yet supported in any version of VS Code, neither in the local installation, nor in the remote version, but this might come at some point in future, see https://github.com/Octoframes/jupyter_compare_view/issues/6.

**Comment by kolibril13** [comment]
Maybe you can try this now again
