### ISSUE TITLE
support VS Code

### ISSUE THREAD

**Issue by christopher-besch** [Octoframes/jupyter_compare_view#6]

**Comment by kolibril13** [comment]
For debugging one open the VS Code Command Palette via Shift + Command + P and then search for 
`Developer: Toggle Developer Tools`

**Comment by christopher-besch** [comment]
Personal note: this is quite definitely a problem with jupyter_compare_view attaching it's source to a parent that doesn't exist in VSC but is present in Jupyter Lab directly.

**Comment by JGameCreation** [comment]
+1 for this feature

**Comment by kolibril13** [comment]
solved by #41 .
